from django.core.exceptions import ValidationError
from django.test import TestCase, Client


# Create your tests here.

# class ExampleTests(TestCase):
#     def test_example(self):
#         with self.assertRaises(ValidationError):
#             raise ValidationError('test')
